<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="expression_extended" nsURI="http://www.example.org/expression_extended"
    nsPrefix="expression_extended">
  <eClassifiers xsi:type="ecore:EClass" name="Multiply" eSuperTypes="../../expression.model/model/expression.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="ecore:EClass ../../expression.model/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="ecore:EClass ../../expression.model/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
